// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjy_bpHrSLyQ2pgo1EjICX9iI6R623aeM',
    appId: '1:95113090396:web:66519421de1432130c1d99',
    messagingSenderId: '95113090396',
    projectId: 'cold-assistant-ai',
    authDomain: 'cold-assistant-ai.firebaseapp.com',
    storageBucket: 'cold-assistant-ai.firebasestorage.app',
    measurementId: 'G-4Q4TQENX6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03apm8x_mRuREZSmdZnjk6Bn_4ybKstI',
    appId: '1:95113090396:android:65a27626222700db0c1d99',
    messagingSenderId: '95113090396',
    projectId: 'cold-assistant-ai',
    storageBucket: 'cold-assistant-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7_tTYo87rcPa-_42AWzq5Wh9Qr2EPbnA',
    appId: '1:95113090396:ios:53a53d0017c2da1a0c1d99',
    messagingSenderId: '95113090396',
    projectId: 'cold-assistant-ai',
    storageBucket: 'cold-assistant-ai.firebasestorage.app',
    iosBundleId: 'com.mert.coldAssistantAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7_tTYo87rcPa-_42AWzq5Wh9Qr2EPbnA',
    appId: '1:95113090396:ios:fd0516c9f1a380cb0c1d99',
    messagingSenderId: '95113090396',
    projectId: 'cold-assistant-ai',
    storageBucket: 'cold-assistant-ai.firebasestorage.app',
    iosBundleId: 'com.example.coldAssistantAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjy_bpHrSLyQ2pgo1EjICX9iI6R623aeM',
    appId: '1:95113090396:web:61bb26c253ae190c0c1d99',
    messagingSenderId: '95113090396',
    projectId: 'cold-assistant-ai',
    authDomain: 'cold-assistant-ai.firebaseapp.com',
    storageBucket: 'cold-assistant-ai.firebasestorage.app',
    measurementId: 'G-EQ47KXB93C',
  );
}
